export const COMPONENT_TYPES = {
  TEXT: "text",
  BUTTON: "button",
  CONTAINER: "container",
  STACK: "stack",
  CARD: "card",
  TEXT_FIELD: "textField",
  CHECKBOX: "checkbox",
  SWITCH: "switch",
  RADIO: "radio",
  ICON: "icon",
  LIST_VIEW: "listView",
  SLIDER: "slider",
  DROPDOWN_BUTTON: "dropdownButton",
  TABLE: "table",
}
