export const COMPONENT_TYPES = {
  TEXT: "text",
  BUTTON: "button",
  CONTAINER: "container",
  ROW: "row",
  COLUMN: "column",
  STACK: "stack",
  CARD: "card",
  TEXT_FIELD: "textField",
  CHECKBOX: "checkbox",
  SWITCH: "switch",
  RADIO: "radio",
  ICON: "icon",
  LIST_VIEW: "listView",
  APP_BAR: "appBar",
  SLIDER: "slider",
  DROPDOWN_BUTTON: "dropdownButton",
  SELECT: "select",
  TABLE: "table",
  FORM: "form",
  INPUT: "input",
}
